# Generated by Django 4.1.1 on 2022-09-11 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_description', models.CharField(max_length=40)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='profile_pics')),
                ('likes', models.ManyToManyField(related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
