# Generated by Django 4.1.1 on 2022-09-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=130),
        ),
    ]
