# Generated by Django 4.1.1 on 2022-09-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProject', '0002_alter_product_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_football_sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_description', models.CharField(max_length=130)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='product_hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_description', models.CharField(max_length=130)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='product_pant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_description', models.CharField(max_length=130)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='product_sneakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_description', models.CharField(max_length=130)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='product_t_shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_description', models.CharField(max_length=130)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='profile_pics')),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
