# Generated by Django 4.1.1 on 2022-09-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProject', '0004_rename_product_name_product_sneakers_productname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_sneakers',
            old_name='productName',
            new_name='product_name',
        ),
    ]
