# Generated by Django 4.1.1 on 2022-09-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProject', '0005_rename_productname_product_sneakers_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_football_sneaker',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_hat',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_pant',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_sneakers',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_t_shirt',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_football_sneaker',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='product_hat',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='product_pant',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='product_sneakers',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='product_t_shirt',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
