# Generated by Django 4.1.1 on 2022-09-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProject', '0006_product_football_sneaker_date_product_hat_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_football_sneaker',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product_hat',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product_pant',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product_sneakers',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product_t_shirt',
            name='date',
        ),
        migrations.AlterField(
            model_name='product_football_sneaker',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='product_hat',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='product_pant',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='product_sneakers',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='product_t_shirt',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
