# Generated by Django 4.1.1 on 2022-09-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProject', '0007_remove_product_football_sneaker_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_football_sneaker',
            name='product_image',
            field=models.ImageField(default=0, upload_to='profile_pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_hat',
            name='product_image',
            field=models.ImageField(default=0, upload_to='profile_pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_pant',
            name='product_image',
            field=models.ImageField(default=0, upload_to='profile_pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_sneakers',
            name='product_image',
            field=models.ImageField(default=0, upload_to='profile_pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_t_shirt',
            name='product_image',
            field=models.ImageField(default=0, upload_to='profile_pics'),
            preserve_default=False,
        ),
    ]
