# Generated by Django 4.1.1 on 2022-09-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProject', '0008_alter_product_football_sneaker_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_sneakers',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
