# Generated by Django 4.1.1 on 2022-09-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProject', '0002_alter_product_football_sneaker_product_image_and_more'),
        ('appProject', '0010_product_football_sneaker_date_product_hat_date_and_more'),
    ]

    operations = [
    ]
