# Generated by Django 4.1.1 on 2022-09-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProject', '0011_merge_20220915_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_football_sneaker',
            old_name='date',
            new_name='product_date',
        ),
        migrations.RenameField(
            model_name='product_hat',
            old_name='date',
            new_name='product_date',
        ),
        migrations.RenameField(
            model_name='product_pant',
            old_name='date',
            new_name='product_date',
        ),
        migrations.RenameField(
            model_name='product_sneakers',
            old_name='date',
            new_name='product_date',
        ),
        migrations.RenameField(
            model_name='product_t_shirt',
            old_name='date',
            new_name='product_date',
        ),
        migrations.AlterField(
            model_name='product_sneakers',
            name='product_image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
