# Generated by Django 4.1.1 on 2022-09-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProject', '0013_alter_product_football_sneaker_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_football_sneaker',
            name='product_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product_hat',
            name='product_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product_pant',
            name='product_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product_sneakers',
            name='product_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product_t_shirt',
            name='product_date',
            field=models.DateTimeField(null=True),
        ),
    ]
