# Generated by Django 4.1.1 on 2022-09-17 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProject', '0015_alter_product_football_sneaker_product_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_football_sneaker',
            name='product_date',
        ),
        migrations.RemoveField(
            model_name='product_hat',
            name='product_date',
        ),
        migrations.RemoveField(
            model_name='product_pant',
            name='product_date',
        ),
        migrations.RemoveField(
            model_name='product_sneakers',
            name='product_date',
        ),
        migrations.RemoveField(
            model_name='product_t_shirt',
            name='product_date',
        ),
    ]
