# Generated by Django 4.1.1 on 2022-09-17 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appProject', '0016_remove_product_football_sneaker_product_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_sneakers',
            name='likes',
            field=models.ManyToManyField(related_name='products_sneakers', to=settings.AUTH_USER_MODEL),
        ),
    ]
