# Generated by Django 4.1.1 on 2022-09-17 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appProject', '0018_alter_product_sneakers_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_t_shirt',
            name='likes',
            field=models.ManyToManyField(related_name='t_shirts', to=settings.AUTH_USER_MODEL),
        ),
    ]
