# Generated by Django 4.1.1 on 2022-09-17 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appProject', '0019_product_t_shirt_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_football_sneakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_description', models.CharField(max_length=130)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('likes', models.ManyToManyField(related_name='football_sneakers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='product_football_sneaker',
        ),
        migrations.AddField(
            model_name='product_hat',
            name='likes',
            field=models.ManyToManyField(related_name='hats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product_pant',
            name='likes',
            field=models.ManyToManyField(related_name='pants', to=settings.AUTH_USER_MODEL),
        ),
    ]
