# Generated by Django 4.1.1 on 2022-09-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProject', '0021_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_media',
            name='website_url',
        ),
    ]
